# Generated by Django 5.1.5 on 2025-01-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_management', '0003_comment_bloglike'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
